---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubenews
  name: kubenews
  namespace: devops
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels: 
      app: kubenews 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50% 
      maxUnavailable: 0%      
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: mganalistati/kube-news:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
            #volumeMounts:
            #- mountPath: /kube-new
            #name: kube-new
        ports:
        - protocol: TCP 
          containerPort: 8080
          name: app-news-port
        env:
        - name: DB_HOST
          value: svc-postgres
        - name: DB_DATABASE
          value: kubenews
        - name: DB_USERNAME
          value: kubenews
        - name: DB_PASSWORD
          value: kub3n3w$
          #volumes:
          #- name: kube-new
          #emptyDir:
          #sizeLimit: 350Mi        
      dnsPolicy: ClusterFirst
      restartPolicy: Always      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubenews
  name: svc-kubenews
  namespace: devops
spec:
  selector:
    app: kubenews
  ports:
  - protocol: TCP
    port: 80
    targetPort: app-news-port
    nodePort: 30000
  type: NodePort
